Exporters:
- ExporterType: Sharesies
  Email: ''
  Password: ''
  PortfolioId: ''
- ExporterType: Csv
  Path: 'import.csv'
  PortfolioId: ''
Importers:
- ImporterType: Sharesight
  CliendId: ''
  ClientSecret: ''
- ImporterType: Csv
  Path: 'export.csv'