name: .NET

on:
  push:
    branches: [ master ]
  create:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Check Tag
      id: check-tag
      run: |
        if [[ ${{ github.event.ref }} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=match::true
        fi
        
    - name: Run Unit Tests
      run: |
        dotnet restore
        dotnet build
        dotnet test test/SharesightImporter.Tests -v m
        
    - name: Build Release
      if: steps.check-tag.outputs.match == 'true'
      run: |
        dotnet restore
        dotnet publish --runtime win10-x64 -c Release /p:PublishReadyToRun=false /p:PublishSingleFile=true /p:UseAppHost=true -o /tmp/SharesightImporter.${GITHUB_RUN_NUMBER} || true
        cd /tmp/
        zip -r SharesightImporter.${GITHUB_RUN_NUMBER}.zip SharesightImporter.${GITHUB_RUN_NUMBER}
        
    - name: Gets Latest Release
      id: latest_release_info
      uses: jossef/action-latest-release-info@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        
    - name: Upload Release Asset
      if: steps.check-tag.outputs.match == 'true'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        upload_url: ${{ steps.latest_release_info.outputs.upload_url }} 
        asset_path: /tmp/SharesightImporter.${GITHUB_RUN_NUMBER}.zip
        asset_name: SharesightImporter.${GITHUB_RUN_NUMBER}.zip
        asset_content_type: application/zip
        
