name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Check Tag
      id: check-tag
      run: |
        if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo ::set-output name=match::true
        fi
    - name: test_unit_testing
      run: |
        dotnet restore
        dotnet build
        dotnet test test/SharesightImporter.Tests -v m
    - name: release_github
      if: steps.check-tag.outputs.match == 'true'
      run: |
        dotnet restore
        dotnet publish --runtime win10-x64 --self-contained true -c Release /p:PublishReadyToRun=false /p:PublishSingleFile=true /p:UseAppHost=true -o /tmp/SharesightImporter.${GITHUB_RUN_NUMBER} || true
        cd /tmp/
        zip -r SharesightImporter.${GITHUB_RUN_NUMBER}.zip SharesightImporter.${GITHUB_RUN_NUMBER}
        
